### ISSUE TITLE
Doesn't work on my device

### ISSUE THREAD

**Issue by momo-the-monster** [chucknology/TangoRoot#1]
Status never changes from 'Not Rooted' after pressing button.

Model number: Project Tango Tablet Development Kit
Android version: 4.4.2
Android security patch level: 2015-12-01
Kern version: 3.10.24-gd25b167 Tango@Atap #1
Build number: KOT49H.160224

**Comment by russellbarnes** [comment]
Same issue here with identical stats.  It doesn't change after reboot, either.

**Comment by nxgraphics** [comment]
same issue doesnt work

**Comment by wirelessdreamer** [comment]
same here, doesn't work.

**Comment by nuernber** [comment]
This used to work on mine, but now it doesn't after installing a new OTA update. I can confirm that it does not work on build KOT49H.160224 (Kernel from Feb. 24, 2016). But it does work on build KOT49H.150811 (Kernel from Aug. 11, 2015).

**Comment by gildardoperez** [comment]
It doesn't work for Build number: KOT49H.161129

**Comment by ShapeShifter499** [comment]
Add another me too post for me.  I also have KOT49H.161129
